kind: Deployment
apiVersion: app/v1
metadata:
  name: medicure-project
  labels:
    app: medicure-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure-project
  template:
    metadata:
      labels:
        app: medicure-project
    spec:
      containers:
      - name: medicure-project
        image: vikramsharma1992/medicure:1
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: medicure-project
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodeport: 30000
  selector:
    app: medicure-project
